[package]
name = "computation"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
orx-parallel = { git = "https://github.com/orxfun/orx-parallel", branch = "feat/redesign-abstractions-api-wasm-support", default-features = false }

[features]
default = []
wasm = ["orx-parallel/wasm"]
